Part A: NumPy Basics (10 Marks)
Q1. Creating Arrays (2 Marks)
Create the following NumPy arrays:
•	A 1D array with values: 10, 20, 30, 40, 50
•	A 2D array (3×3) with values from 1 to 9
Print both arrays and display their shape.


In [1]:
import numpy as np

# Create a 1D array with values 10, 20, 30, 40, 50
arr1d = np.array([10, 20, 30, 40, 50])

# Create a 2D array (3x3) with values from 1 to 9
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


# Printing both arrays
print("1D Array:")
print(arr1d)
print("\nShape of 1D Array:", arr1d.shape)

print("\n2D Array (3x3):")
print(arr2d)
print("\nShape of 2D Array:", arr2d.shape)

1D Array:
[10 20 30 40 50]

Shape of 1D Array: (5,)

2D Array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of 2D Array: (3, 3)


Q2. Array Operations (2 Marks)
Given two arrays:
A = [2, 4, 6, 8]
B = [1, 3, 5, 7]
Perform:
•	Addition
•	Subtraction
•	Multiplication
•	Division


In [2]:
import numpy as np

# Given arrays
A = np.array([2, 4, 6, 8])
B = np.array([1, 3, 5, 7])

# Perform operations
print("Array A:", A)
print("Array B:", B)
print("-" * 50)

print(f"\nAddition     (A + B): {A + B}")
print(f"Subtraction  (A - B): {A - B}")
print(f"Multiplication (A * B): {A * B}")
print(f"Division     (A / B): {A / B}")

Array A: [2 4 6 8]
Array B: [1 3 5 7]
--------------------------------------------------

Addition     (A + B): [ 3  7 11 15]
Subtraction  (A - B): [1 1 1 1]
Multiplication (A * B): [ 2 12 30 56]
Division     (A / B): [2.         1.33333333 1.2        1.14285714]


Q3. Statistical Functions (3 Marks)
Create a NumPy array:
data = [12, 15, 20, 25, 30, 35]
Find:
•	Mean
•	Median
•	Standard deviation
•	Maximum value


In [3]:
import numpy as np

# Create the array
data = np.array([12, 15, 20, 25, 30, 35])

# Calculate statistical measures
mean_value = np.mean(data)
median_value = np.median(data)
std_value = np.std(data)
max_value = np.max(data)

# Print results
print("Data Array:", data)
print("="*40)
print(f"Mean                : {mean_value}")
print(f"Median              : {median_value}")
print(f"Standard Deviation  : {std_value:.4f}")
print(f"Maximum Value       : {max_value}")

Data Array: [12 15 20 25 30 35]
Mean                : 22.833333333333332
Median              : 22.5
Standard Deviation  : 8.0709
Maximum Value       : 35


Q4. Reshaping Arrays (3 Marks)
Create a NumPy array of numbers from 1 to 12.
Then:
•	Reshape it into a 3×4 matrix
•	Reshape it into a 4×3 matrix
Display both results.


In [4]:
import numpy as np

# Create array from 1 to 12
arr = np.arange(1, 13)

print("Original:", arr)
print("Shape:", arr.shape)
print()

# Reshape to 3x4
print("3x4 Matrix:")
print(arr.reshape(3, 4))
print()

# Reshape to 4x3
print("4x3 Matrix:")
print(arr.reshape(4, 3))

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4x3 Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Part B: Pandas Basics (10 Marks)
Q5. Creating DataFrame (3 Marks)
Create a Pandas DataFrame with the following data:
Name	Age	Marks
Ali	20	85
Sara	21	90
John	19	78
Ayesha	22	88
Display the DataFrame and print its summary.


In [5]:
import pandas as pd

# Create DataFrame
data = {
    'Name': ['Ali', 'Sara', 'John', 'Ayesha'],
    'Age': [20, 21, 19, 22],
    'Marks': [85, 90, 78, 88]
}

df = pd.DataFrame(data)

# Display DataFrame
print("Student Data:")
print(df)
print("\n" + "="*40)
print("DataFrame Summary:")
print(df.info())
print("\nStatistical Summary:")
print(df.describe())

Student Data:
     Name  Age  Marks
0     Ali   20     85
1    Sara   21     90
2    John   19     78
3  Ayesha   22     88

DataFrame Summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Marks   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None

Statistical Summary:
             Age      Marks
count   4.000000   4.000000
mean   20.500000  85.250000
std     1.290994   5.251984
min    19.000000  78.000000
25%    19.750000  83.250000
50%    20.500000  86.500000
75%    21.250000  88.500000
max    22.000000  90.000000


Q6. Data Selection (2 Marks)
From the above DataFrame:
•	Display only the Name and Marks columns
•	Display students whose Marks are greater than 85


In [6]:
import pandas as pd

# Create DataFrame (from Q5)
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'Ayesha'],
    'Age': [20, 21, 19, 22],
    'Marks': [85, 90, 78, 88]
})

print("="*50)
print("STUDENT DATA")
print("="*50)
print(df)
print("\n" + "="*50)

# 1. Display only Name and Marks columns
print("\n1. Name and Marks Columns Only:")
print("="*50)
print(df[['Name', 'Marks']])

# 2. Display students with Marks > 85
print("\n2. Students with Marks > 85:")
print("="*50)
print(df[df['Marks'] > 85])

STUDENT DATA
     Name  Age  Marks
0     Ali   20     85
1    Sara   21     90
2    John   19     78
3  Ayesha   22     88


1. Name and Marks Columns Only:
     Name  Marks
0     Ali     85
1    Sara     90
2    John     78
3  Ayesha     88

2. Students with Marks > 85:
     Name  Age  Marks
1    Sara   21     90
3  Ayesha   22     88


Q7. Handling Missing Values (3 Marks)
Create a DataFrame with some missing values:
data = {
    'Name': ['Ali', 'Sara', 'John', None],
    'Marks': [85, None, 78, 88]
}
Tasks:
•	Find missing values
•	Replace missing values with appropriate values
•	Display cleaned DataFrame


In [7]:
import pandas as pd
import numpy as np

# Create DataFrame with missing values
data = {
    'Name': ['Ali', 'Sara', 'John', None],
    'Marks': [85, None, 78, 88]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\n" + "="*50)

# 1. Find missing values
print("\n1. Finding Missing Values:")
print("-"*40)
print("Missing Values Summary:")
print(df.isnull())
print("\nCount of Missing Values:")
print(df.isnull().sum())

# 2. Replace missing values
print("\n2. Replacing Missing Values:")
print("-"*40)

# Replace Name: None -> 'Unknown'
df['Name'] = df['Name'].fillna('Unknown')

# Replace Marks: None -> Mean Marks
mean_marks = df['Marks'].mean()
df['Marks'] = df['Marks'].fillna(mean_marks)

# 3. Display cleaned DataFrame
print("Cleaned DataFrame:")
print(df)

Original DataFrame:
   Name  Marks
0   Ali   85.0
1  Sara    NaN
2  John   78.0
3  None   88.0


1. Finding Missing Values:
----------------------------------------
Missing Values Summary:
    Name  Marks
0  False  False
1  False   True
2  False  False
3   True  False

Count of Missing Values:
Name     1
Marks    1
dtype: int64

2. Replacing Missing Values:
----------------------------------------
Cleaned DataFrame:
      Name      Marks
0      Ali  85.000000
1     Sara  83.666667
2     John  78.000000
3  Unknown  88.000000


Q8. Basic Data Analysis (2 Marks)
Using the student DataFrame:
•	Find average marks
•	Find highest marks
•	Find lowest marks


In [8]:
import pandas as pd

# Create DataFrame
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'Ayesha'],
    'Age': [20, 21, 19, 22],
    'Marks': [85, 90, 78, 88]
})

print("Student Data:")
print(df)
print("\n" + "="*40)

# Find statistics
average_marks = df['Marks'].mean()
highest_marks = df['Marks'].max()
lowest_marks = df['Marks'].min()

print("\nMarks Statistics:")
print(f"Average Marks: {average_marks}")
print(f"Highest Marks: {highest_marks}")
print(f"Lowest Marks: {lowest_marks}")

Student Data:
     Name  Age  Marks
0     Ali   20     85
1    Sara   21     90
2    John   19     78
3  Ayesha   22     88


Marks Statistics:
Average Marks: 85.25
Highest Marks: 90
Lowest Marks: 78
