Task 1: Creating Arrays (15 Minutes)
Write Python code to:
a) Create a NumPy array containing: [language=Python] [10, 20, 30, 40, 50]
b) Display:
• Array values
• Data type
• Shape of the array
c) Create a two-dimensional array:


1 2 3
4 5 6
7 8 9



In [1]:
import numpy as np

# Task a: Create a NumPy array
arr1 = np.array([10, 20, 30, 40, 50])

# Task b: Display array values, data type, and shape
print("--- One-dimensional Array ---")
print("Array values:", arr1)
print("Data type:", arr1.dtype)
print("Shape of the array:", arr1.shape)
print()

# Task c: Create a two-dimensional array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Display the 2D array
print("--- Two-dimensional Array ---")
print("Array values:")
print(arr2)
print("Data type:", arr2.dtype)
print("Shape of the array:", arr2.shape)

--- One-dimensional Array ---
Array values: [10 20 30 40 50]
Data type: int64
Shape of the array: (5,)

--- Two-dimensional Array ---
Array values:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type: int64
Shape of the array: (3, 3)


Task 2: Special Arrays (15 Minutes)
Create the following arrays using NumPy functions:
a) Array of zeros with size 5.
b) Array of ones with size 8.
c) Array containing numbers from 1 to 20.
d) Array containing even numbers from 2 to 20.
e) Array with 10 equally spaced values between 0 and 1.

In [3]:
import numpy as np

# Task a: Array of zeros with size 5
zeros_array = np.zeros(5)
print("a) Array of zeros (size 5):")
print(zeros_array)
print()

# Task b: Array of ones with size 8
ones_array = np.ones(8)
print("b) Array of ones (size 8):")
print(ones_array)
print()

# Task c: Array containing numbers from 1 to 20
range_array = np.arange(1, 21)
print("c) Numbers from 1 to 20:")
print(range_array)
print()

# Task d: Array containing even numbers from 2 to 20
even_array = np.arange(2, 21, 2)
print("d) Even numbers from 2 to 20:")
print(even_array)
print()

# Task e: Array with 10 equally spaced values between 0 and 1
linspace_array = np.linspace(0, 1, 10)
print("e) 10 equally spaced values between 0 and 1:")
print(linspace_array)

a) Array of zeros (size 5):
[0. 0. 0. 0. 0.]

b) Array of ones (size 8):
[1. 1. 1. 1. 1. 1. 1. 1.]

c) Numbers from 1 to 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

d) Even numbers from 2 to 20:
[ 2  4  6  8 10 12 14 16 18 20]

e) 10 equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Task 3: Array Indexing and Slicing (20 Minutes)
Given the array:
[language=Python] arr = np.array([5,10,15,20,25,30,35,40])
Perform the following:
a) Print the first element.
b) Print the last element.
c) Print elements from index 2 to 5.
d) Print the first four elements.
e) Print all elements except the first two.


In [4]:
import numpy as np

# Given array
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])

print("Original array:", arr)
print()

# Task a: Print the first element
print("a) First element:", arr[0])

# Task b: Print the last element
print("b) Last element:", arr[-1])

# Task c: Print elements from index 2 to 5
print("c) Elements from index 2 to 5:", arr[2:6])

# Task d: Print the first four elements
print("d) First four elements:", arr[:4])

# Task e: Print all elements except the first two
print("e) All elements except first two:", arr[2:])

Original array: [ 5 10 15 20 25 30 35 40]

a) First element: 5
b) Last element: 40
c) Elements from index 2 to 5: [15 20 25 30]
d) First four elements: [ 5 10 15 20]
e) All elements except first two: [15 20 25 30 35 40]


Task 4: Mathematical Operations (20 Minutes)
Create:
[language=Python] A = np.array([1,2,3,4,5]) B = np.array([10,20,30,40,50])
Perform:
a) Addition
b) Subtraction
c) Multiplication
d) Division
e) Square each element of array A

In [5]:
import numpy as np
# Create the arrays
A = np.array([1, 2, 3, 4, 5])
B = np.array([10, 20, 30, 40, 50])

print("Array A:", A)
print("Array B:", B)
print()

# Task a: Addition
addition = A + B
print("a) Addition (A + B):", addition)

# Task b: Subtraction
subtraction = A - B
print("b) Subtraction (A - B):", subtraction)

# Task c: Multiplication
multiplication = A * B
print("c) Multiplication (A * B):", multiplication)

# Task d: Division
division = A / B
print("d) Division (A / B):", division)

# Task e: Square each element of array A
squared = A ** 2
print("e) Square of each element in A:", squared)

Array A: [1 2 3 4 5]
Array B: [10 20 30 40 50]

a) Addition (A + B): [11 22 33 44 55]
b) Subtraction (A - B): [ -9 -18 -27 -36 -45]
c) Multiplication (A * B): [ 10  40  90 160 250]
d) Division (A / B): [0.1 0.1 0.1 0.1 0.1]
e) Square of each element in A: [ 1  4  9 16 25]


Task 5: Two-Dimensional Arrays (20 Minutes)
Create the matrix:


2 4 6
8 10 12
14 16 18


Then:
a) Print the shape of the matrix.
b) Print the element in row 2, column 3.
c) Print the first row.
d) Print the second column.
e) Calculate the sum of all elements.

In [7]:
import numpy as np
# Create the matrix
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

print("Matrix:")
print(matrix)
print()

# Task a: Print the shape of the matrix
print("a) Shape of the matrix:", matrix.shape)

# Task b: Print the element in row 2, column 3
# Note: Python uses 0-based indexing, so row 2 is index 1, column 3 is index 2
print("b) Element at row 2, column 3:", matrix[1, 2])

# Task c: Print the first row
print("c) First row:", matrix[0, :])

# Task d: Print the second column
print("d) Second column:", matrix[:, 1])

# Task e: Calculate the sum of all elements
print("e) Sum of all elements:", np.sum(matrix))

Matrix:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

a) Shape of the matrix: (3, 3)
b) Element at row 2, column 3: 12
c) First row: [2 4 6]
d) Second column: [ 4 10 16]
e) Sum of all elements: 90


Task 6: Statistical Functions (15 Minutes)
Given:
[language=Python] marks = np.array([78,85,92,67,88,95,73,81])
Find:
a) Maximum value
b) Minimum value
c) Mean
d) Median
e) Standard deviation

In [8]:
import numpy as np

# Given array
marks = np.array([78, 85, 92, 67, 88, 95, 73, 81])

print("Marks array:", marks)
print()

# Task a: Maximum value
print("a) Maximum value:", np.max(marks))

# Task b: Minimum value
print("b) Minimum value:", np.min(marks))

# Task c: Mean
print("c) Mean:", np.mean(marks))

# Task d: Median
print("d) Median:", np.median(marks))

# Task e: Standard deviation
print("e) Standard deviation:", np.std(marks))

Marks array: [78 85 92 67 88 95 73 81]

a) Maximum value: 95
b) Minimum value: 67
c) Mean: 82.375
d) Median: 83.0
e) Standard deviation: 8.915401000515905


Challenge Task (15 Minutes)
Create a NumPy array containing the marks of 10 students.
Write a program to:
1. Calculate the average marks.
2. Find the highest and lowest marks.
3. Display all marks greater than the average

In [9]:
import numpy as np

# Create array with marks of 10 students
marks = np.array([78, 85, 92, 67, 88, 95, 73, 81, 90, 76])

print("Marks of 10 students:", marks)
print()

# 1. Calculate the average marks
average = np.mean(marks)
print(f"1. Average marks: {average:.2f}")

# 2. Find the highest and lowest marks
highest = np.max(marks)
lowest = np.min(marks)
print(f"2. Highest marks: {highest}")
print(f"   Lowest marks: {lowest}")
print()

# 3. Display all marks greater than the average
marks_above_avg = marks[marks > average]
print(f"3. Marks greater than average ({average:.2f}):")
print(f"   {marks_above_avg}")
print(f"   Count: {len(marks_above_avg)} students")

Marks of 10 students: [78 85 92 67 88 95 73 81 90 76]

1. Average marks: 82.50
2. Highest marks: 95
   Lowest marks: 67

3. Marks greater than average (82.50):
   [85 92 88 95 90]
   Count: 5 students
