Part A: Setup (5 Minutes)
Task 1: Import NumPy
Write a Python program to:
1.	Import NumPy using the alias np.
2.	Display the installed NumPy version.


In [ ]:
import numpy as np

# Display the installed NumPy version
print(np.__version__)

2.0.2


Part B: Array Creation (10 Minutes)
Task 2: Create Arrays
Create the following arrays:
1.	A 1-D array containing numbers 1 to 10.
2.	A 2-D array of size 3×3 containing values 1 to 9.
3.	An array from a Python list [5, 10, 15, 20, 25].
Sample Output
[1 2 3 4 5 6 7 8 9 10]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# Task 2: Create Arrays

# 1. A 1-D array containing numbers 1 to 10
array1 = np.arange(1, 11)
print(array1)

# 2. A 2-D array of size 3x3 containing values 1 to 9
array2 = np.arange(1, 10).reshape(3, 3)
print("\n", array2)  # \n adds a blank line for better readability

# 3. An array from a Python list [5, 10, 15, 20, 25]
array3 = np.array([5, 10, 15, 20, 25])
print("\n", array3)

[ 1  2  3  4  5  6  7  8  9 10]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [ 5 10 15 20 25]


In [ ]:
# Using the 3x3 array (array2)
print("Array being analyzed:")
print(array2)
print()

# 1. Display its shape
print("Shape:", array2.shape)

# 2. Display its dimensions (ndim)
print("Dimensions:", array2.ndim)

# 3. Display total number of elements (size)
print("Size:", array2.size)

# 4. Display data type (dtype)
print("Datatype:", array2.dtype)

Array being analyzed:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Dimensions: 2
Size: 9
Datatype: int64


Part D: Indexing and Slicing (10 Minutes)
Task 4: Access Elements
For the array:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
Perform:
1.	Print the first element.
2.	Print the last element.
3.	Print elements from index 2 to 6.
4.	Print every second element.
5.	Print the reverse array.


In [ ]:
import numpy as np

# Create the array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Display the original array
print("Original array:", arr)
print()

#      Task 4: Access Elements

# 1. Print the first element
print("1. First element:", arr[0])

# 2. Print the last element
print("2. Last element:", arr[-1])

# 3. Print elements from index 2 to 6
print("3. Elements from index 2 to 6:", arr[2:7])  # 2:7 includes indices 2,3,4,5,6

# 4. Print every second element
print("4. Every second element:", arr[::2])

# 5. Print the reverse array
print("5. Reverse array:", arr[::-1])

Original array: [ 10  20  30  40  50  60  70  80  90 100]

1. First element: 10
2. Last element: 100
3. Elements from index 2 to 6: [30 40 50 60 70]
4. Every second element: [10 30 50 70 90]
5. Reverse array: [100  90  80  70  60  50  40  30  20  10]



Part E: Mathematical Operations (10 Minutes)
Task 5: Perform Arithmetic Operations
Create:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
Find:
1.	Addition
2.	Subtraction
3.	Multiplication
4.	Division
5.	Square of array a
Expected Example
Addition: [6 6 6 6 6]




In [ ]:
import numpy as np

# Create the arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Display the original arrays
print("Array a:", a)
print("Array b:", b)
print()

# ============ Task 5: Perform Arithmetic Operations ============

# 1. Addition
addition = a + b
print("1. Addition:", addition)

# 2. Subtraction
subtraction = a - b
print("2. Subtraction:", subtraction)

# 3. Multiplication
multiplication = a * b
print("3. Multiplication:", multiplication)

# 4. Division
division = a / b
print("4. Division:", division)

# 5. Square of array a
square_a = a ** 2
print("5. Square of array a:", square_a)

Array a: [1 2 3 4 5]
Array b: [5 4 3 2 1]

1. Addition: [6 6 6 6 6]
2. Subtraction: [-4 -2  0  2  4]
3. Multiplication: [5 8 9 8 5]
4. Division: [0.2 0.5 1.  2.  5. ]
5. Square of array a: [ 1  4  9 16 25]


Part F: Special Arrays (5 Minutes)
Task 6: Generate Special Arrays
Create:
1.	Array of zeros with size 5.
2.	Array of ones with size 5.
3.	Identity matrix of size 4×4.
4.	Array of numbers from 0 to 20 with step size 2.
Functions to Use
np.zeros()
np.ones()
np.eye()
np.arange()

In [ ]:
import numpy as np

# ============ Part F: Special Arrays ============
print("============ Part F: Special Arrays ============")

# 1. Array of zeros with size 5
zeros_array = np.zeros(5)
print("1. Array of zeros (size 5):", zeros_array)

# 2. Array of ones with size 5
ones_array = np.ones(5)
print("2. Array of ones (size 5):", ones_array)

# 3. Identity matrix of size 4×4
identity_matrix = np.eye(4)
print("3. Identity matrix (4×4):")
print(identity_matrix)

# 4. Array of numbers from 0 to 20 with step size 2
range_array = np.arange(0, 21, 2)
print("4. Array from 0 to 20 with step 2:", range_array)

============ Part F: Special Arrays ============
1. Array of zeros (size 5): [0. 0. 0. 0. 0.]
2. Array of ones (size 5): [1. 1. 1. 1. 1.]
3. Identity matrix (4×4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4. Array from 0 to 20 with step 2: [ 0  2  4  6  8 10 12 14 16 18 20]


Part G: Statistics (5 Minutes)
Task 7: Basic Statistical Operations
For the array:
data = np.array([12,15,18,20,22,25,30])
Calculate:
1.	Mean
2.	Median
3.	Maximum value
4.	Minimum value
5.	Sum of all elements


In [ ]:
import numpy as np

# ============ Part G: Statistics ============
print("============ Part G: Statistics ============")

# Create the array
data = np.array([12, 15, 18, 20, 22, 25, 30])

print("Data array:", data)
print()

# 1. Mean
mean_value = np.mean(data)
print("1. Mean:", mean_value)

# 2. Median
median_value = np.median(data)
print("2. Median:", median_value)

# 3. Maximum value
max_value = np.max(data)
print("3. Maximum value:", max_value)

# 4. Minimum value
min_value = np.min(data)
print("4. Minimum value:", min_value)

# 5. Sum of all elements
sum_value = np.sum(data)
print("5. Sum of all elements:", sum_value)

============ Part G: Statistics ============
Data array: [12 15 18 20 22 25 30]

1. Mean: 20.285714285714285
2. Median: 20.0
3. Maximum value: 30
4. Minimum value: 12
5. Sum of all elements: 142
